baseURL: https://karavel.io/
languageCode: en-us
title: The Karavel Project
theme: karavel
copyright: Copyright 2021 The Karavel Project
defaultContentLanguage: en
languages:
  en:
    weight: 1
    params:
      footer: |
        [GitHub](https://github.com/karavel-io)
        [Discuss](https://github.com/karavel-io/community/discussions)
        [Twitter](https://twitter.com/karavelproject)
        [Discord](https://discord.gg/ZrKBndbmje)

